[project]
name = "video-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python",
    "numpy",
    "ruff",
    "confluent-kafka>=2.8.2",
    "flask>=3.1.0",
    "kafka-python>=2.0.5",
]
